name: Ruby
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.2']
    steps:
    - uses: actions/checkout@v2
    - name: Install dependent libralies
      run: sudo apt install -y libmysqlclient-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup Database
      run: |
        cp config/database.yml.ci config/database.yml
        sudo systemctl start mysql
        bundle exec rails db:create
        bundle exec rails db:schema:load
      env:
        RAILS_ENV: test
    - name: Run tests
      run: bundle exec rspec
    - name: Archive rspec result screenshots
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: rspec result screenshots
        path: tmp/screenshots/
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Set AWS region
      run: aws configure set region ap-northeast-1
    - name: Run AWS CodeDeploy
      run: aws deploy create-deployment --application-name RailsDeployDemo --deployment-group-name TestGroup --github-location repository="MrFuku/rails_0820",commitId="${{ github.sha }}"
